//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialsCalculator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int MaterialID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Square { get; set; }
        public string Price { get; set; }
        public string Count { get; set; }
        public Nullable<int> MaterialTypeID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual MaterialType MaterialType { get; set; }
    }
}
